# Generated by Django 4.0 on 2021-12-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Student',
        ),
    ]
