# Generated by Django 4.0 on 2021-12-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_rename_detail_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentDetail',
        ),
    ]
